name: meeting_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3
  contained_tab_bar_view: ^0.1.0
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.2
  flutter_hooks: ^0.14.1
  flutter_mobx: ^1.1.0+2
  flutter_svg: ^0.19.1
  mobx: ^1.2.1+3
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  mobx_codegen: ^1.1.1+1

flutter:

  assets:
    - assets/banner.png
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Light.ttf
          weight: 200
